### ISSUE TITLE
Sub64 does not produce accurate results with negative numbers

### ISSUE THREAD

**Issue by StevenToth** [JohnCGriffin/overflow#1]
I'm not currently using the library, but was reviewing it as I was interested in how various libraries were handling operations that would potentially overflow the provided data types.  I noticed a number of the functions were not properly handling subtraction of negative numbers and wanted to pass along the information.

func Sub64 in overflow_impl.go does not indicate an overflow when subtracting a large int64 from a negative int64.

**Example of Sub64(-100000, math.MaxInt64):**
```
func main() {
	var a, b int64
	a = -100000
	b = math.MaxInt64
	c, overflow := Sub64(a, b)
	fmt.Printf("Using Sub64: %d - %d = %d, overflow = %v\n", a, b, c, overflow)

	bigA := big.NewInt(a)
	bigB := big.NewInt(b)
	bigC := big.NewInt(0)
	bigC.Sub(bigA, bigB)
	fmt.Printf("Using big.Int: %d - %d = %d, overflow = %v, results matched = %v", bigA, bigB, bigC, !bigC.IsInt64(), bigC == big.NewInt(c)) 
}
```

**Output:**
Using Sub64: -100000 - 9223372036854775807 = 9223372036854675809, overflow = false
Using big.Int: -100000 - 9223372036854775807 = -9223372036854875807, overflow = true, results matched = false

Playground: https://play.golang.org/p/Y2-3NlUEPO4

**Comment by JohnCGriffin** [comment]
Hi Steven,

Thank you so much for the reported flaw.  I will definitely address it and
let you know.

Thanks again,
John Griffin

**Comment by JohnCGriffin** [comment]
Hi again Steven,

I think that you were expected the second value in the returned tuple to
mean (the-value, overflow?) when it's really returning
(the-value, ok).  So, when you saw (overflow == false) it really meant (ok
== false).  In other words, good operations return true and bad operations
return false.

One thing that bothers me is I'm returning the bad value as well.  I
probably should just change the non-value to its zero value.

Let me know if I misunderstood and thanks again for the notice.

-John Griffin

**Comment by StevenToth** [comment]
You are correct.  My sincere apologies, I misinterpreted the interface.  Sorry to take up your time and thank you for getting back to me and clarifying.

**Comment by JohnCGriffin** [comment]
No problem.  Don't feel bad about the mistake, because I wrote the thing
and was baffled for several minutes.   Go is still not natural for me.

Actually, this is a good example of where some languages utilize
Option<Type>,  an Option<Type> either has a value or it doesn't and you
cannot accidentally use it.

Thanks,
John Griffin
